### ISSUE TITLE
lme doesn't work with ggemmeans, but it does in emmeans

### ISSUE THREAD

**Issue by mamscience** [strengejacke/ggeffects#169]
Hi
I've been building a linear mixed model and I want to display marginal means. I managed to pull the data manually from emmeans but I cannot through ggemmeans. 

When I feed ggemmeans the model it throws an error instead, saying:
```
Reason: 'arg' should be one of “containment”, “satterthwaite”, “appx-satterthwaite”, “auto”, “boot-satterthwaite”
You may try 'ggpredict()' or 'ggeffect()'.
```
However, if I pass the model directly into emmeans I don't get such an error. I tried to pass the "mode" argument to fix this (at least I think this is the argument the error refers to), but it only throws more errors. 

I've attached the reprex. Please ignore the other error in throws, it's because the model is supersimplified and the data is not meaningful.

Thanks in advance!
Michel

```
library(nlme)
library(ggeffects)
reprex <- data.frame(time = c(0,1,2,3,4, 0, 1,2,3,4), group=c(1,1,1,1,1, 2,2,2,2,2), id=c(10,10,10,10,10,15,15,15,15,15), sum=c(0,5,10,15,20, 0,20,25,45,50))

reprexmodel <-  lme(log(sum+1)  ~ time * group,        
                                random  = ~ 1|id,
                                correlation = corAR1(form =~  as.numeric(time)| id), 
                                data=reprex, na.action = na.exclude)

ggemmeans(reprexmodel, c("time [all]","group")) %>% plot(colors="hero")
```

**Comment by strengejacke** [comment]
Thanks, should be fixed.

**Comment by mamscience** [comment]
> Thanks, should be fixed.

Thanks for your quick fix. Unfortunately the error still persists.

```
> ggemmeans(model, c("time, "group"))
Can't compute marginal effects, 'emmeans::emmeans()' returned an error.

Reason: 'arg' should be one of “containment”, “satterthwaite”, “appx-satterthwaite”, “auto”, “boot-satterthwaite”
You may try 'ggpredict()' or 'ggeffect()'.

NULL
```

**Comment by strengejacke** [comment]
Please provide a full reproducible example, including session info, so I can check. For me, everything works fine:

``` r
library(magrittr)
library(nlme)
library(ggeffects)
reprex <- data.frame(time = c(0,1,2,3,4, 0, 1,2,3,4), group=c(1,1,1,1,1, 2,2,2,2,2), id=c(10,10,10,10,10,15,15,15,15,15), sum=c(0,5,10,15,20, 0,20,25,45,50))

reprexmodel <-  lme(log(sum+1)  ~ time * group,        
                    random  = ~ 1|id,
                    correlation = corAR1(form =~  as.numeric(time)| id), 
                    data=reprex, na.action = na.exclude)

ggemmeans(reprexmodel, c("time [all]","group")) %>% plot(colors="hero")
#> Lade nötigen Namensraum: emmeans
#> Model has log-transformed response. Back-transforming predictions to original response scale. Standard errors are still on the log-scale.
#> Lade nötigen Namensraum: ggplot2
```

![](https://i.imgur.com/GXPjAus.png)

<sup>Created on 2020-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Did you update _ggeffects_ from GitHub?

**Comment by mamscience** [comment]
Yes I updated ggeffects to 0.16.0.1

SessionInfo included: 

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggeffects_0.16.0.1

loaded via a namespace (and not attached):
 [1] tidyr_1.1.2         splines_4.0.3       foreach_1.5.1       carData_3.0-4       statmod_1.4.35      stats4_4.0.3       
 [7] cellranger_1.1.0    yaml_2.2.1          pillar_1.4.6        backports_1.1.10    lattice_0.20-41     glue_1.4.2         
[13] digest_0.6.27       ggsignif_0.6.0      minqa_1.2.4         colorspace_1.4-1    sandwich_3.0-0      MuMIn_1.43.17      
[19] htmltools_0.5.0     Matrix_1.2-18       survey_4.0          pkgconfig_2.0.3     broom_0.7.2         haven_2.3.1        
[25] purrr_0.3.4         xtable_1.8-4        mvtnorm_1.1-1       scales_1.1.1        openxlsx_4.2.3      rio_0.5.16         
[31] lme4_1.1-25         emmeans_1.5.2-1     tibble_3.0.4        effects_4.2-0       generics_0.0.2      car_3.0-10         
[37] ggplot2_3.3.2       sjlabelled_1.1.7    ellipsis_0.3.1      ggpubr_0.4.0        TH.data_1.0-10      nnet_7.3-14        
[43] TMB_1.7.18          survival_3.2-7      magrittr_1.5        crayon_1.3.4        readxl_1.3.1        evaluate_0.14      
[49] estimability_1.3    nlme_3.1-149        MASS_7.3-53         rstatix_0.6.0       forcats_0.5.0       foreign_0.8-80     
[55] GLMMadaptive_0.7-15 tools_4.0.3         data.table_1.13.2   hms_0.5.3           mitools_2.4         lifecycle_0.2.0    
[61] matrixStats_0.57.0  multcomp_1.4-14     munsell_0.5.0       zip_2.1.1           DHARMa_0.3.3.0      compiler_4.0.3     
[67] tinytex_0.26        rlang_0.4.8         grid_4.0.3          nloptr_1.2.2.2      iterators_1.0.13    rstudioapi_0.11    
[73] rmarkdown_2.5       boot_1.3-25         gtable_0.3.0        codetools_0.2-16    abind_1.4-5         DBI_1.1.0          
[79] curl_4.3            R6_2.5.0            zoo_1.8-8           knitr_1.30          dplyr_1.0.2         insight_0.10.0.1   
[85] stringi_1.5.3       parallel_4.0.3      Rcpp_1.0.5          vctrs_0.3.4         tidyselect_1.1.0    xfun_0.18          
[91] coda_0.19-4        
```

I'll be back in a minute with a reprex

**Comment by strengejacke** [comment]
strange, indeed...

**Comment by strengejacke** [comment]
ah, ok! glad to know it works!
