### ISSUE TITLE
Error in names(datlist) <- names(focal_terms): 'names' attribute [1] must be the same length as the vector [0]

### ISSUE THREAD

**Issue by Richie-nomas** [strengejacke/ggeffects#222]
Hello, I'm trying to use ggpredict function in my GEE model (geepack), with the following code.

``` r
library(geepack)
#> Warning: replacing previous import 'vctrs::data_frame' by 'tibble::data_frame'
#> when loading 'dplyr'
library(ggeffects)
Riqueza<- c(4,4,9,11,12,14,9,8,9,6,8,6,6,6,6,5,4,5,5,5,5,7,7,7,7,3,4,2,1)
Area<- c(469.35741,503.22325,512.18286,454.64775,411.40569,311.42162,232.03441, 
         194.09921,172.53853,140.23875,124.35800,106.04346,146.43975,230.59296,
         235.93046,173.79332,152.20300,120.36225,94.65690, 86.00561, 73.68068,
         67.42349,61.76505,53.24691,42.17096,38.67824,35.13629,20.48685,162.09020)
C8<-as.data.frame(cbind(Riqueza,Area))
model7<-geeglm(Riqueza~Area,C8, id = rep(1, 29), family = poisson, corstr = "ar1")

ggpredict(model7, "Area")
#> Warning: Could not get model data.
#> Error in names(datlist) <- names(focal_terms): 'names' attribute [1] must be the same length as the vector [0]
```

<sup>Created on 2021-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Unfortunately, I don't know how to solve that error. 
Does anyone have the same problem with geeglm objects? 
Thanks for your help.

**Comment by strengejacke** [comment]
Thanks, should be fixed with the next update from the _insight_ package, which is responsible for retrieving model data.

**Comment by dannysack** [comment]
Hello, I am getting the exact same issue, although it looks like there has been an update in _insight_ since you posted. Do you have any thoughts into why this is still not working, thanks!

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by dannysack** [comment]
Sure thing, it seems to be a problem when addressing imputed datasets, if I only create a model for one imputed dataset it is okay, but if I do it across all imputed datasets it does not work for `geeglm`, however it does work for `glmer` in `lme4`! See below:

``` r
library(geepack)
library(tidyverse)
library(mice)
library(ggeffects)
library(lme4)

df <- data.frame(id = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 , 1, 
                        1, 1, 1, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
                        6, 6, 6, 6, 6, 6),
                 y = c(1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
                       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
                       1, 1, 1, 1, 1, 1),
                 exp = sample(c(0,1), size = 50, replace = TRUE),
                 em = c(59, NA, 60, 50, 57, 56, 52, 50, 49, 50, 57, 57, 51, 58, 60, 57,
                        57, 59, NA, 52, 60, 49, 59, 59, 60, 58, 60, NA, 60, 58, 47, 54,
                        59, 60, 59, 54, 60, NA, 60, 58, 59, 59, 60, 58, 57, NA, 60, 58,
                        60, 58))

imp <- mice(df, m = 5, seed = 10)

# this version works
mod <- geeglm(y ~ exp*em, 
              data = complete(imp, 1),
              id = id,
              family = binomial,
              corstr = "exchangeable")

ggpredict(mod, "exp")

# this version does not work
mods <- complete(imp, "all") %>%
  map(~ geeglm(y ~ exp*em, 
               data = .x,
               id = id,
               family = binomial,
               corstr = "exchangeable"))


ggpredict(mods$`1`, c("exp", "em"))

# this verison does not work either
mods1 <- with(imp, geeglm(y ~ exp*em,
                          id = id,
                          family = binomial,
                          corstr = "exchangeable"))

ggpredict(mods1$analyses[[1]], "exp")

# mods version does not work with pool_predictions either
mods %>%
  map(~ ggpredict(.x, "exp")) %>%
  pool_predictions()

# it does, however, work with glmer in lme4 despite some warnings
glmm_mod <- complete(imp, "all") %>%
  map(~ glmer(formula = y ~ exp*em + (1 | id),
              family = binomial,
              data = .x))

# pool predictions
glmm_mod %>%
  map(~ ggpredict(.x, "exp")) %>%
  pool_predictions()
```
