### ISSUE TITLE
hypothesis_test function unable to calculate standard errors: solution or alternative?

### ISSUE THREAD

**Issue by Helsinki-Ronan** [strengejacke/ggeffects#296]
Hi, 

I am running the attached zero-inflated mixed effects model (available as a .RDS file).  I am trying to predict pairwise comparisons but I run into the following errors. I was wondering is there a work around or alternative?

# Error 1
When I run the following code

`all_prey_empty_stomach<- ggpredict(feast_or_famine_all_prey_df, type = "zi_prob"),
hypothesis_test(all_prey_empty_stomach, c("vgll3_scaled", "gross_sea_age"))
`

I get the following error message: `Objects of class ggalleffects are not yet supported.`

Fair enough. So I attempted this alternative

# Error 2
`all_prey_empty_stomach_2<- ggpredict(feast_or_famine_all_prey_df, type = "zi_prob", c("vgll3_scaled", "gross_sea_age"))
hypothesis_test(all_prey_empty_stomach_2)`

This time the error message read: `Error: Unable to compute standard errors for this model.`

Cheers,
Ronan

[all_prey_model.zip](https://github.com/strengejacke/ggeffects/files/11027467/all_prey_model.zip)

**Comment by strengejacke** [comment]
I think this is an issue with _marginaleffects_. @vincentarelbundock can you take a look at the sample model? 

``` r
library(marginaleffects)
library(glmmTMB)
x <- readRDS("C:/Users/mail/Desktop/all_prey_model.RDS")
out <- predictions(x, variable = c("vgll3_scaled", "gross_sea_age"))
#> Error: Unable to compute standard errors for this model.
```

<sup>Created on 2023-03-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
@Helsinki-Ronan Do you have the code that fitted the model?

**Comment by Helsinki-Ronan** [comment]
Thanks for the reply! Here's the code:

`feast_or_famine_all_prey_df<- glmmTMB(num_prey ~ season + fishing_season + genetic_sex + condition_scaled + best_estimate_reporting_group_north_south + gross_sea_age/(vgll3_scaled+six6_scaled+residuals_fork_length) + (1|location),
data = data_5, family = nbinom2, ziformula = ~ .,  dispformula = ~ fishing_season + best_estimate_reporting_group_north_south,
   control = glmmTMBControl(optimizer=optim, optArgs=list(method="BFGS"), profile = T, collect = FALSE))`

**Comment by vincentarelbundock** [comment]
@strengejacke do you know how `insight` builds the variance covariance matrix here? `insight::get_varcov(model, components = "all")` returns a 34x34, whereas `stats::vcov` returns 3 different matrices.

If `insight` were just binding them, I would expect to see lots of zeros, but I don't.

**Comment by strengejacke** [comment]
It's just `stats::vcov(x, full = TRUE)`, which is supported by glmmTMB.

**Comment by vincentarelbundock** [comment]
Thanks for the report. I think (hope) this is fixed in the development version of `marginaleffects` on Github.

**Comment by Helsinki-Ronan** [comment]
Just tried this after installing the `marginaleffects` development version and I still get the same errors, I'm afraid.

**Comment by vincentarelbundock** [comment]
Did you restart R? What does ˋpackageVersion("marginaleffects")` say?

**Comment by Helsinki-Ronan** [comment]
I did restart R after installing the development version of the package from GitHub. Running the command `packageVersion("marginaleffects")`  returns '0.11.0.9016’.

**Comment by strengejacke** [comment]
Thanks Vicnent,
can confirm that the issues are fixed now.

``` r
library(glmmTMB)
library(marginaleffects)

m <- readRDS("c:/Users/mail/Desktop/all_prey_model.RDS")
out <- predictions(m, variable = c("vgll3_scaled", "gross_sea_age"))
summary(out)
#> 
#>  Estimate Std. Error    z Pr(>|z|) 2.5 % 97.5 %
#>        30       8.25 3.63   <0.001  13.8   46.1
#> 
#> Columns: estimate, std.error, statistic, p.value, conf.low, conf.high

library(ggeffects)
p <- ggpredict(m, type = "zi_prob", c("vgll3_scaled", "gross_sea_age"))
hypothesis_test(p)
#> # Linear trend for vgll3_scaled
#> 
#> gross_sea_age | Contrast |          95% CI |     p
#> --------------------------------------------------
#> 1SW-MSW       |     6.36 | [-11.21, 23.93] | 0.478
#> 
#> Contrasts are presented on the response-scale.
```

<sup>Created on 2023-03-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


``` r
sessionInfo()
#> R version 4.2.3 (2023-03-15 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 22621)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
#> [3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
#> [5] LC_TIME=German_Germany.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.31     withr_2.5.0       R.methodsS3_1.8.2 lifecycle_1.0.3  
#>  [5] magrittr_2.0.3    reprex_2.0.2      evaluate_0.20     rlang_1.1.0      
#>  [9] cli_3.6.0         fs_1.6.1          R.utils_2.12.2    R.oo_1.25.0      
#> [13] vctrs_0.6.1       rmarkdown_2.20    styler_1.9.1      tools_4.2.3      
#> [17] R.cache_0.16.0    glue_1.6.2        purrr_1.0.1       xfun_0.37        
#> [21] yaml_2.3.7        fastmap_1.1.1     compiler_4.2.3    htmltools_0.5.4  
#> [25] knitr_1.42
```

@Helsinki-Ronan Not sure if you still need to update some packages? For me, everything works.

**Comment by strengejacke** [comment]
> '0.11.0.9016’.

I think the build on r-universe was not compiled yet. try

`` r
remotes::install_github("vincentarelbundock/marginaleffects")
```

**Comment by Helsinki-Ronan** [comment]
`remotes::install_github("vincentarelbundock/marginaleffects")`

Yep this solved it and all is working now. Thank you both for your time with this issue!
