### ISSUE TITLE
ggpredict produces single predicted value for continuous variable

### ISSUE THREAD

**Issue by carolinebrandt** [strengejacke/ggeffects#405]
I am trying to get the predicted probabilities from a rare-events logit.

When I try ggpredict, I get a single data-point, instead of the representative values I would expect (see: https://github.com/strengejacke/ggeffects/issues/220)

I have tried updating all the packages from their github sources.

Dataset can be found here: https://ucdp.uu.se/downloads/nsos/ucdp-onesided-231-csv.zip

```
rm(list = ls())
library(foreign)
library(ggeffects)
library(logistf) 

df = read.csv("~/ucdp-onesided-211.csv")
df$best_fatality_estimate = log(df$best_fatality_estimate + 1)

#Making some of the values 0, to reproduce the error
index = sample(1:nrow(df), 100, replace=FALSE) 
df$best_fatality_estimate[index] = 0 

#Making up some independent and dependent variables 
df$dv = rbinom(nrow(df), 1, 0.1)
df$iv = runif(nrow(df), min=0, max=100)
df$iv2 = rnorm(nrow(df), 100, sd=20)

reg <- logistf(dv~best_fatality_estimate+year  + iv + iv2, data = df)

ggeffects::ggpredict(reg, terms="best_fatality_estimate")
```

![image](https://github.com/strengejacke/ggeffects/assets/10762565/c2f3c108-77fa-4b5b-8449-f6c1ac76efd8)

```
ggeffects::ggpredict(reg, terms="best_fatality_estimate [all]")
```
![image](https://github.com/strengejacke/ggeffects/assets/10762565/2cd3c62c-bc18-44bd-8b54-986f230e7ff1)

Interestingly, ggeffects works:

```
ggeffects::ggeffect(reg, terms="best_fatality_estimate")
```
![image](https://github.com/strengejacke/ggeffects/assets/10762565/5b6fa03d-028d-4a32-a814-529f731acf78)

**Comment by strengejacke** [comment]
Thanks, should now work, including `flic()` and `flac()`:

``` r
library(datawizard)
library(ggeffects)
library(logistf)

d <- data_read("c:/Users/mail/Downloads/ucdp-onesided-231-csv.zip")
d$best_fatality_estimate <- log(d$best_fatality_estimate + 1)

set.seed(1234)
# Making some of the values 0, to reproduce the error
index <- sample(1:nrow(d), 100, replace = FALSE)
d$best_fatality_estimate[index] <- 0

# Making up some independent and dependent variables
d$dv <- rbinom(nrow(d), 1, 0.1)
d$iv <- runif(nrow(d), min = 0, max = 100)
d$iv2 <- rnorm(nrow(d), 100, sd = 20)

reg <- logistf(dv ~ best_fatality_estimate + year + iv + iv2, data = d)

ggpredict(reg, terms = "best_fatality_estimate")
#> Data were 'prettified'. Consider using `terms="best_fatality_estimate
#>   [all]"` to get smooth plots.
#> # Predicted probabilities of dv
#> 
#> best_fatality_estimate | Predicted |       95% CI
#> -------------------------------------------------
#>                      0 |      0.13 | [0.09, 0.20]
#>                      2 |      0.12 | [0.09, 0.16]
#>                      4 |      0.11 | [0.10, 0.13]
#>                      6 |      0.10 | [0.08, 0.13]
#>                      8 |      0.10 | [0.06, 0.14]
#>                     10 |      0.09 | [0.05, 0.15]
#>                     12 |      0.08 | [0.04, 0.16]
#>                     14 |      0.07 | [0.03, 0.18]
#> 
#> Adjusted for:
#> * year = 2004.00
#> *   iv =   49.67
#> *  iv2 =  100.72

ggpredict(flic(reg), terms = "best_fatality_estimate")
#> Data were 'prettified'. Consider using `terms="best_fatality_estimate
#>   [all]"` to get smooth plots.
#> # Predicted probabilities of dv
#> 
#> best_fatality_estimate | Predicted |       95% CI
#> -------------------------------------------------
#>                      0 |      0.13 | [0.09, 0.19]
#>                      2 |      0.12 | [0.09, 0.15]
#>                      4 |      0.11 | [0.10, 0.13]
#>                      6 |      0.10 | [0.08, 0.13]
#>                      8 |      0.09 | [0.06, 0.13]
#>                     10 |      0.09 | [0.05, 0.14]
#>                     12 |      0.08 | [0.04, 0.16]
#>                     14 |      0.07 | [0.03, 0.17]
#> 
#> Adjusted for:
#> * year = 2004.00
#> *   iv =   49.67
#> *  iv2 =  100.72

ggpredict(flac(reg, data = d), terms = "best_fatality_estimate")
#> Data were 'prettified'. Consider using `terms="best_fatality_estimate
#>   [all]"` to get smooth plots.
#> # Predicted probabilities of dv
#> 
#> best_fatality_estimate | Predicted |       95% CI
#> -------------------------------------------------
#>                      0 |      0.13 | [0.09, 0.19]
#>                      2 |      0.12 | [0.09, 0.15]
#>                      4 |      0.11 | [0.09, 0.13]
#>                      6 |      0.10 | [0.08, 0.13]
#>                      8 |      0.09 | [0.06, 0.14]
#>                     10 |      0.09 | [0.05, 0.15]
#>                     12 |      0.08 | [0.04, 0.16]
#>                     14 |      0.07 | [0.03, 0.18]
#> 
#> Adjusted for:
#> * year = 2004.00
#> *   iv =   49.67
#> *  iv2 =  100.72
```

<sup>Created on 2023-11-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by carolinebrandt** [comment]
First - *thank you* - I am deeply appreciative. 

I am uncertain why I am still getting a single data point.
```

rm(list = ls())
remotes::install_github("easystats/datawizard")
library(datawizard)
remotes::install_github("strengejacke/ggeffects")
library(ggeffects)
library(logistf)

d = read.csv("/Users/cbrandt/Dropbox/AAA_Projects/UNSC/data/ucdp-onesided-211.csv")
d$best_fatality_estimate <- log(d$best_fatality_estimate + 1)

set.seed(1234)
# Making some of the values 0, to reproduce the error
index <- sample(1:nrow(d), 100, replace = FALSE)
d$best_fatality_estimate[index] <- 0

# Making up some independent and dependent variables
d$dv <- rbinom(nrow(d), 1, 0.1)
d$iv <- runif(nrow(d), min = 0, max = 100)
d$iv2 <- rnorm(nrow(d), 100, sd = 20)

reg <- logistf(dv ~ best_fatality_estimate + year + iv + iv2, data = d)

ggpredict(reg, terms = "best_fatality_estimate")
```
<img width="713" alt="Screenshot 2023-11-21 at 12 11 09 PM" src="https://github.com/strengejacke/ggeffects/assets/10762565/328831a8-e239-4775-860e-28fb102518d9">



<img width="729" alt="Screenshot 2023-11-21 at 12 11 21 PM" src="https://github.com/strengejacke/ggeffects/assets/10762565/bf1d19b6-1eb0-4aea-a49b-7c87eebe3c09">

<img width="748" alt="Screenshot 2023-11-21 at 12 11 30 PM" src="https://github.com/strengejacke/ggeffects/assets/10762565/b92f469b-2228-4345-85df-26b77e9b8ca8">

**Comment by strengejacke** [comment]
I think you may have not updated the latest version? Try `ggeffects::install_latest(force = TRUE)`.

**Comment by carolinebrandt** [comment]
Yes! My apologies - and THANK YOU
