### ISSUE TITLE
error ggpredict() with glmmTMB with offset-term

### ISSUE THREAD

**Issue by ohmengmodi** [strengejacke/ggeffects#72]
Using ggpredict() with a mixed negative-binomial zero-inflated model using glmmTMB with an offset-term, I get the following error:
Fehler in offset(rec.hours.dec) : Objekt 'rec.hours.dec' nicht gefunden
My model contains the offset as 
m1<-glmmTMB(resp ~  pred1  + pred2 + pred3  + (1|plot/subplot) + offset(log(rec.hours.dec)), family="nbinom2", se=T , REML=F ,ziformula = ~1)
I updated the corresponding packages, without any change in the error.
Many thanks
M

**Comment by strengejacke** [comment]
This is an issue in _insight_:

``` r
library(insight)
library(glmmTMB)
data("Salamanders")

m1 <- glmmTMB(
  count ~ mined + (1 | site) + offset(Wtemp), 
  zi =  ~ 1, 
  family = nbinom2, 
  data = Salamanders
)

m2 <- glmmTMB(
  count ~ mined + offset(Wtemp) + (1 | site), 
  zi =  ~ 1, 
  family = nbinom2, 
  data = Salamanders
)

find_formula(m1)
#> $conditional
#> count ~ mined
#> 
#> $random
#> ~1 | site

find_formula(m2)
#> $conditional
#> count ~ mined + offset(Wtemp)
#> 
#> $random
#> ~1 | site
```

As my regular expression knowledge is too limited to currently find a solution, I'd suggest you just re-write your formula and put the offset-term before the random term(s).

**Comment by strengejacke** [comment]
After updating _insight_ from GitHub, this should work now.

**Comment by KuepferA** [comment]
Thank you - I have the same issue. I tried to install _insight_ but I still get the same error. 
Any help is much appreciated.

**Comment by KuepferA** [comment]
Here is my reproducible example:

[ReproducibleExample_GitHub.zip](https://github.com/strengejacke/ggeffects/files/5591885/ReproducibleExample_GitHub.zip)
